'use client';

import '@/app/globals.css';

import { Provider } from 'jotai';

import { DebugAtoms } from '@/components/functional/DebugAtoms';

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body>
        <Provider>
          <DebugAtoms />
          {children}
        </Provider>
      </body>
    </html>
  );
}
